### ISSUE TITLE
respimg locks up my machine for 2 mins

### ISSUE THREAD

**Issue by leehambley** [nwtn/grunt-respimg#25]
Probably a function of having too many SVGs, but I have a fairly conservative pipeline of settings.

`respimg` portion of my `Gruntfile.js`:

```
    respimg: {
      options: {
        pngCompressionLevel: 3,
        widths:  [ 160, 320, 640, 1280, 2560 ],
        optimize: {
          input:  { svgo: 0, image_optim: 0, picopt: 0, imageOptim: 0 },
          output: { svgo: 0, image_optim: 0, picopt: 0, imageOptim: 0 }
        }
      },
      default: {
        files: [{
          expand: true,
          cwd: 'assets/images/src/',
          src: ['**/*'],
          dest: 'assets/images/'
        }]
      },
    },
```

(I want SVG->PNG only, and the 5 sizes)

The time comes down if I remove the larger images, but not enough to make the problem go away (5 sizes `108s`, 4 sizes `75s`, 3 sizes `48s`)

We don't have that many images in the source directory (23 svgs).

What I can't understand is why even running the same build twice with the same options takes so long, I tried to follow the source, but I couldn't find anything to compare the ages (mtimes) of the inputs and possible existing output to avoid wasting time on unnecessary work?

I don't mind a task that takes a long time, but crippling my machine for a couple of minutes is horrendous, I'd rather it took longer, but I could still type and/or switch windows, what am I doing wrong?

**Comment by jGleitz** [comment]
Could you report the size of your RAM and its usage when grunt-respimg runs?

I have similar issues and got to know the code quite well. I think the problem here is that for 23 images and 5 sizes, 23 * 5 = 115  phantomjs processes will be spawned. I am quite sure that my machine gets shut down because of that. 

There are multiple downsides of so many processes (no efficient caching because of constant, costly context changes, other processes don't get enough execution time, etc.), but most importantly, phantomjs processes have a high memory usage (~ 250 MB per process on my machine). Thus, RAM gets full quite fast and the OS starts to swap to disk, at which point my OS almost freezes.

**Comment by leehambley** [comment]
@jGleitz honestly, it'd be worth it for me to use Make to avoid doing the work based purely on the file mtimes.

Machine is a 3 GHz Intel Core i7, with 8 GB DDR3 (2013 macbook) but you're right, probably the machine just flat-out starts swapping. I can't really get into benchmarking and tracking the resource usage.

**Comment by nwtn** [comment]
closing because this repo is not maintained
